# Lab Task 01

In [1]:
import numpy as np

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [6]:
#code here
array = np.arange(9)
reshaped = array.reshape(-1, 3)
reshaped

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
array1 = np.arange(3)
array2 = np.arange(3)

res = np.concatenate((array1, array2), axis=0)
print('horizontally:', res)

res = np.vstack((array1, array2))
print('vertically:\n', res)

horizontally: [0 1 2 0 1 2]
vertically:
 [[0 1 2]
 [0 1 2]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [41]:
#code here
imp_keywords = ['important', 'critical', 'urgent', 'attention']
pro_keywords = ['offers', 'offer', 'deal', 'best', 'price']
spam_keywords = ['not spam', 'cost', 'free']
imp_l  = []
pro_l  = []
spam_l  = []


emails = ['this email is very important Mr.James', 'We will provide free Iphones', 'get ready for rent free housing', 'jazzcash has a new offer', 'intel is providing a buy 1 get 1 deal', 'attention all students, be ready for quiz.']


for email in emails:

  if ( any(word in imp_keywords for word in email.lower().split()) ):
    imp_l.append(email)
  elif ( any(word in pro_keywords for word in email.lower().split()) ):
    pro_l.append(email)
  elif ( any(word in spam_keywords for word in email.lower().split()) ):
    spam_l.append(email)

print("imp",imp_l)
print("pro",pro_l)
print("spam", spam_l)

imp ['this email is very important Mr.James', 'attention all students, be ready for quiz.']
pro ['jazzcash has a new offer', 'intel is providing a buy 1 get 1 deal']
spam ['We will provide free Iphones', 'get ready for rent free housing']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [43]:
#code here
eng_span = {
    'hello': 'ola',
    'I am': "soye",
    'james': 'dora',
    'one': 'uno',
    'two': 'dos',
    'three': 'tres',
}

print("Press q to Exit.\n")
choice = ''

while choice != 'q':
  choice = input('Enter a word: ')

  if choice == 'q':
    print("\nExiting...")
    break

  span = eng_span.get(choice, 'None found')

  print(f'\nEnglish : {choice} \nSpanish : {span}')


Press q to Exit.
Enter a word: joe
English : joe 
Spanish : None found
Enter a word: one
English : one 
Spanish : uno
Enter a word: dos
English : dos 
Spanish : None found
Enter a word: hello
English : hello 
Spanish : ola
Enter a word: i am
English : i am 
Spanish : None found
Enter a word: james
English : james 
Spanish : dora
Enter a word: q
Exiting...


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [44]:
import pandas as pd

In [45]:
dataset = pd.read_csv('/content/vgsalesGlobale.csv')
dataset.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [47]:
# task 1

total_sales = dataset['Global_Sales'].sum()
print("Total: ", total_sales)

Total:  8920.44


In [52]:
# task 2

max_index = dataset['Global_Sales'].idxmax()
dataset['Name'].iloc[max_index]

'Wii Sports'

In [140]:
# task 3

na_sales = dataset['NA_Sales'].mean()
print("Avg NA: ", na_sales)

EU_sales = dataset['EU_Sales'].mean()
print("Avg EU: ", EU_sales)

JP_sales = dataset['JP_Sales'].mean()
print("Avg JP: ", JP_sales)

o_sales = dataset['Other_Sales'].mean()
print("Avg Other: ", o_sales)

Avg NA:  0.26466742981082064
Avg EU:  0.14665200626581515
Avg JP:  0.077781660441017
Avg Other:  0.0480630196409206


In [117]:
# task 4

grouped = dataset.groupby('Genre')
sales = grouped['Global_Sales'].sum()
top_5_genres = sales.sort_values(ascending=False).head(5)
top_5_genres_names = top_5_genres.index.tolist()

print(top_5_genres_names)
print("\nDetails: \n")
print(top_5_genres)

['Action', 'Sports', 'Shooter', 'Role-Playing', 'Platform']

Details: 

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [91]:
# task 5

print('NA Sales: \n')
grouped['NA_Sales'].sum()

NA Sales: 



Genre
Action          877.83
Adventure       105.80
Fighting        223.59
Misc            410.24
Platform        447.05
Puzzle          123.78
Racing          359.42
Role-Playing    327.28
Shooter         582.60
Simulation      183.31
Sports          683.35
Strategy         68.70
Name: NA_Sales, dtype: float64

In [105]:
print("Most popular genre in NA: ")
# grouped['NA_Sales'].sum().sort_values(ascending=False).head(1)
grouped['NA_Sales'].sum().idxmax()

Most popular genre in NA: 


'Action'

In [92]:
print('EU Sales: \n')
grouped['EU_Sales'].sum()

EU Sales: 



Genre
Action          525.00
Adventure        64.13
Fighting        101.32
Misc            215.98
Platform        201.63
Puzzle           50.78
Racing          238.39
Role-Playing    188.06
Shooter         313.27
Simulation      113.38
Sports          376.85
Strategy         45.34
Name: EU_Sales, dtype: float64

In [96]:
print('JP Sales: \n')
grouped['JP_Sales'].sum()

JP Sales: 



Genre
Action          159.95
Adventure        52.07
Fighting         87.35
Misc            107.76
Platform        130.77
Puzzle           57.31
Racing           56.69
Role-Playing    352.31
Shooter          38.28
Simulation       63.70
Sports          135.37
Strategy         49.46
Name: JP_Sales, dtype: float64

In [109]:
# task 6


dataset.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [122]:
# task 7


top3 = dataset.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)
top3_names = top3.index.tolist()

print(top3_names)
print('\nDetails: \n')
print(top3)

['PS2', 'X360', 'PS3']

Details: 

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [136]:
# task 8

grouped = dataset.groupby('Genre')
sales = grouped['Global_Sales'].sum().sort_values(ascending=False)
genres = sales.index.tolist()
total_sum = sales.sum()
total_sum
for genre in genres:
  market_share = (sales[genre] / total_sum) * 100
  print(f"{genre} : {market_share:.2f} %")



Action : 19.63 %
Sports : 14.92 %
Shooter : 11.63 %
Role-Playing : 10.40 %
Platform : 9.32 %
Misc : 9.08 %
Racing : 8.21 %
Fighting : 5.03 %
Simulation : 4.40 %
Puzzle : 2.75 %
Adventure : 2.68 %
Strategy : 1.96 %


In [139]:
# task 9

coe = dataset['NA_Sales'].corr(dataset['EU_Sales'])

print("Correlation coefficient between NA_Sales and EU_Sales:", coe)

Correlation coefficient between NA_Sales and EU_Sales: 0.7677267483702631


In [138]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
